amcl:
  ros__parameters:
    alpha1: 0.001
    alpha2: 0.01
    alpha3: 0.01
    alpha4: 0.01
    alpha5: 0.02
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 3.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: true
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.1
    update_min_d: 0.1
    use_sim_time: false
    z_hit: 0.9
    z_rand: 0.5
    z_short: 0.05
bt_navigator:
  ros__parameters:
    bt_loop_duration: 10
    default_nav_through_poses_bt_xml: navigate_through_poses_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: navigate_to_pose_w_replanning_and_recovery.xml
    default_server_timeout: 20
    enable_groot_monitoring: true
    global_frame: map
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    odom_topic: /odom
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_controller_cancel_bt_node
    robot_base_frame: base_link
    use_sim_time: false
controller_server:
  ros__parameters:
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      #plugin: "mppi::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.5  # 기존 0.4 → 증가 (회전 반응 향상)
      vx_max: 0.6
      vx_min: -0.35
      vy_max: 0.5
      wz_max: 2.5  # 기존 2.2 → 증가 (더 유연한 방향 전환)
      iteration_count: 1
      prune_distance: 2.0
      transform_tolerance: 0.1
      temperature: 0.4
      gamma: 0.02
      motion_model: "DiffDrive"
      visualize: false
      allow_reversing: true  # 후진 허용 (갇혔을 때 탈출 가능)
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.3
      rotate_to_heading_angular_vel: 0.5

      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3

      AckermannConstrains:
        min_turning_r: 0.35  # 기존 0.3 → 증가 (더 부드러운 회전)

      critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.2

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.4

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0  # 기존 6.0 → 감소 (후진 가능성 높임)
        threshold_to_consider: 0.6

      ObstaclesCritic:
        enabled: true
        cost_power: 1
        repulsion_weight: 2.0  # 기존 2.0 → 증가 (더 강력한 장애물 회피)
        critical_weight: 15.0
        consider_footprint: true
        collision_cost: 10000.0
        collision_margin_distance: 0.1  # 기존 0.15 → 증가 (충돌 방지 거리 확대)
        near_goal_distance: 0.6

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0  # 기존 2.0 → 증가 (경로 정렬 강화)
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.6
        offset_from_furthest: 20
        use_path_orientations: true

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 8.0  # 기존 6.0 → 증가 (경로 추종 강화)
        offset_from_furthest: 5
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        offset_from_furthest: 4
        threshold_to_consider: 0.6
        max_angle_to_furthest: 1.8  # 기존 1.2 → 증가 (더 큰 각도에서 경로 수정 가능)
        forward_preference: true

      Recovery:
        enabled: true
        behavior: ["BackUp", "Spin"]
        backup_distance: 0.2  # 기존 0.3 → 증가 (후진 거리 확장)
        backup_speed: -0.1
        spin_distance: 1.0

      
   
    controller_frequency: 20.0
    controller_plugins:
    - FollowPath
    
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    use_sim_time: false
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false
global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: true
      footprint: '[[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]'
      # footprint_padding: 0.10000000149011612
      global_frame: map
      inflation_layer:
        cost_scaling_factor: 3.0
        # inflation_radius: 1.5
        inflation_radius: 1.5
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          topic: /scan
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer
      publish_frequency: 2.0
      resolution: 0.05
      robot_base_frame: base_link
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      track_unknown_space: true
      update_frequency: 2.0
      use_sim_time: false
local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true
      footprint: '[[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]'
      footprint_padding: 0.10000000149011612
      global_frame: map
      height: 2
      inflation_layer:
        cost_scaling_factor: 2.0
        # cost_scaling_factor: 2.5
        inflation_radius: 0.2
        # inflation_radius: 1.5
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          topic: /scan
      plugins:
      - obstacle_layer
      - inflation_layer
      publish_frequency: 2.0
      resolution: 0.05
      robot_base_frame: base_link
      rolling_window: true
      update_frequency: 5.0
      use_sim_time: false
      width: 5
map_saver:
  ros__parameters:
    free_thresh_default: 0.25
    map_subscribe_transient_local: true
    occupied_thresh_default: 0.65
    save_map_timeout: 5.0
    use_sim_time: false
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ''
planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.5
      use_astar: true
    expected_planner_frequency: 20.0
    planner_plugins:
    - GridBased
    use_sim_time: false
robot_state_publisher:
  ros__parameters:
    use_sim_time: false
velocity_smoother:
  ros__parameters:
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    feedback: CLOSED_LOOP
    max_accel:
    - 2.5
    - 0.0
    - 3.2
    max_decel:
    - -2.5
    - 0.0
    - -3.2
    max_velocity:
    - 0.26
    - 0.0
    - 1.0
    min_velocity:
    - -0.26
    - 0.0
    - -1.0
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    use_sim_time: false
    velocity_timeout: 1.0
waypoint_follower:
  ros__parameters:
    loop_rate: 2000
    stop_on_failure: false
    use_sim_time: false
    wait_at_waypoint:
      enabled: true
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      waypoint_pause_duration: 200
    waypoint_task_executor_plugin: wait_at_waypoint